config/routes.rb
Dragonfruit::Application.routes.draw do

  get "/" => 'static_pages#home', :as => "home"

  post "/", to: 'static_pages#beginProcess'

  post "/games/:id", to: 'games#start'

  post "/games/:id/submit", to: 'games#addImage'

  get "/games/:id/getImages", to: 'games#getImages'

  post "/games/:id/vote", to: 'games#vote'

  get "/games/:id/winner", to: 'games#winner'

  get "/games/:id/source", to: 'games#source'

  resources :games_images

  resources :source_images

  resources :games

  resources :users

  

  match "/help", to: 'static_pages#help'

end

app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessible :gameId, :sourceImage, :started
  validates :gameId, presence: true, uniqueness: true
  validates :sourceImage, presence: true
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  # GET /games
  # GET /games.json
  def index
    @games = Game.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @games }
    end
  end

  # GET /games/1
  # GET /games/1.json
  def show
    logger.debug "Show me the money"
    @game = Game.find(params[:id])
    @sourceUrl = SourceImage.find(@game[:sourceImage])[:url]
    logger.debug @sourceUrl

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/1/source
  # shows source image
  def source
    logger.debug "finding the source"
    logger.debug params[:id]
    sourceId = Game.find(params[:id]).sourceImage
    source = SourceImage.find(sourceId).url
    render json: { :url => source }.to_json
  end

  # POST /games/1/submit
  # adds an image!!!

  def addImage
    logger.debug "Adding image!!!"
    logger.debug params[:id]
    logger.debug params[:url]
    logger.debug params[:name]

    obj = { :gameId => params[:id], :imageUrl => params[:url], :votes => 0, :userSubmitted => params[:name]}
    @added = GamesImage.new(obj)

    if @added.save
      logger.debug "Save went great!"
      render json: {:status => :ok}.to_json
    else
      logger.debug "Something went terribly wrong with the save!!"
    end
    #render :nothing => true
  end

  # GET /games/1/getImages
  # returns the images

  def getImages
    logger.debug "Fetching images..."
    logger.debug params[:id]
    images = GamesImage.find(:all, { :conditions => {:gameId => params[:id] } } )
    logger.debug images
    toReturn = images.map do |e|
      { :url => e.imageUrl, :submittedBy => e.userSubmitted }
    end
    render json: toReturn.to_json
  end

  # POST /games/1/vote
  # vote for an image

  def vote
    logger.debug "Exercising constitutional right to vote..."
    logger.debug params[:id]
    logger.debug params[:userId]
    gameImg = GamesImage.find(:first, { :conditions => { :gameId => params[:id], :userSubmitted => params[:userId]} } )
    gameImg.votes += 1
    if gameImg.save
      logger.debug "Logged your vote!"
      render :nothing => true
    else
      logger.debug "Something went horribly wrong"
    end

  end

  # GET /games/1/winner
  def winner
    logger.debug "And the winner is..."
    logger.debug params[:id]
    winner = GamesImage.find(:first, { :conditions => { :gameId => params[:id] }, :order => 'votes desc' } )
    logger.debug(winner.imageUrl)
    render json: { :url => winner.imageUrl }.to_json
  end

  # POST /games/1
  #you should flip the started bit to TRUE
  def start
    logger.debug "Starting game!!!"
    logger.debug params[:id]
    @game = Game.find(params[:id])
    @sourceUrl = SourceImage.find(@game[:sourceImage])[:url]
    if @game.started == true
      logger.debug "You've already started a game :("
    else
      logger.debug "Starting the game!"
      @game.started = true
      @game.save
      #render :action => "show"
      render :nothing => true
    end
    #render :nothing => true
  end


  # GET /games/new
  # GET /games/new.json
  def new
    @game = Game.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/1/edit
  def edit
    @game = Game.find(params[:id])
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(params[:game])

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render json: @game, status: :created, location: @game }
      else
        format.html { render action: "new" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /games/1
  # PUT /games/1.json
  def update
    @game = Game.find(params[:id])

    respond_to do |format|
      if @game.update_attributes(params[:game])
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :sourceImage %><br />
    <%= f.number_field :sourceImage %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Listing games</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Sourceimage</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @games.each do |game| %>
  <tr>
    <td><%= game.id %></td>
    <td><%= game.sourceImage %></td>
    <td><%= link_to 'Show', game %></td>
    <td><%= link_to 'Edit', edit_game_path(game) %></td>
    <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<!--<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @game.id %>
</p>

<p>
  <b>Sourceimage:</b>
  <%= @game.sourceImage %>
</p>


<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>\

-->

<%= javascript_include_tag "games/games" %>
<%= javascript_include_tag "games/jquery.webcam" %>

<%= button_to "Start Game!", { :action => "start" }, { :id => "startGame", :remote => true } %>

<div id="sourceImg"></div>

<br>

<div id="images"></div>

<div id="winner"></div>

<hr>

<div id="camera"></div>
<div id="status"></div>
<canvas id="canvas" width="320" height="240"></canvas>