config/routes.rb
Dragonfruit::Application.routes.draw do

  get "/" => 'static_pages#home', :as => "home"

  post "/", to: 'static_pages#beginProcess'

  post "/games/:id", to: 'games#start'

  post "/games/:id/submit", to: 'games#addImage'

  get "/games/:id/getImages", to: 'games#getImages'

  post "/games/:id/vote", to: 'games#vote'

  get "/games/:id/winner", to: 'games#winner'

  get "/games/:id/source", to: 'games#source'

  resources :games_images

  resources :source_images

  resources :games

  resources :users

  

  match "/help", to: 'static_pages#help'

end

app/models/source_image.rb
class SourceImage < ActiveRecord::Base
  attr_accessible :id, :url
  
  validates :url, presence: true
end

app/controllers/source_images_controller.rb
class SourceImagesController < ApplicationController
  # GET /source_images
  # GET /source_images.json
  def index
    @source_images = SourceImage.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @source_images }
    end
  end

  # GET /source_images/1
  # GET /source_images/1.json
  def show
    @source_image = SourceImage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @source_image }
    end
  end

  # GET /source_images/new
  # GET /source_images/new.json
  def new
    @source_image = SourceImage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @source_image }
    end
  end

  # GET /source_images/1/edit
  def edit
    @source_image = SourceImage.find(params[:id])
  end

  # POST /source_images
  # POST /source_images.json
  def create
    @source_image = SourceImage.new(params[:source_image])

    respond_to do |format|
      if @source_image.save
        format.html { redirect_to @source_image, notice: 'Source image was successfully created.' }
        format.json { render json: @source_image, status: :created, location: @source_image }
      else
        format.html { render action: "new" }
        format.json { render json: @source_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /source_images/1
  # PUT /source_images/1.json
  def update
    @source_image = SourceImage.find(params[:id])

    respond_to do |format|
      if @source_image.update_attributes(params[:source_image])
        format.html { redirect_to @source_image, notice: 'Source image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @source_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /source_images/1
  # DELETE /source_images/1.json
  def destroy
    @source_image = SourceImage.find(params[:id])
    @source_image.destroy

    respond_to do |format|
      format.html { redirect_to source_images_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/source_images_helper.rb
module SourceImagesHelper
end

app/views/source_images/_form.html.erb
<%= form_for(@source_image) do |f| %>
  <% if @source_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@source_image.errors.count, "error") %> prohibited this source_image from being saved:</h2>

      <ul>
      <% @source_image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/source_images/edit.html.erb
<h1>Editing source_image</h1>

<%= render 'form' %>

<%= link_to 'Show', @source_image %> |
<%= link_to 'Back', source_images_path %>

app/views/source_images/index.html.erb
<h1>Listing source_images</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @source_images.each do |source_image| %>
  <tr>
    <td><%= source_image.id %></td>
    <td><%= source_image.url %></td>
    <td><%= link_to 'Show', source_image %></td>
    <td><%= link_to 'Edit', edit_source_image_path(source_image) %></td>
    <td><%= link_to 'Destroy', source_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Source image', new_source_image_path %>

app/views/source_images/new.html.erb
<h1>New source_image</h1>

<%= render 'form' %>

<%= link_to 'Back', source_images_path %>

app/views/source_images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @source_image.id %>
</p>

<p>
  <b>Url:</b>
  <%= @source_image.url %>
</p>


<%= link_to 'Edit', edit_source_image_path(@source_image) %> |
<%= link_to 'Back', source_images_path %>