config/routes.rb
Dragonfruit::Application.routes.draw do

  get "/" => 'static_pages#home', :as => "home"

  post "/", to: 'static_pages#beginProcess'

  post "/games/:id", to: 'games#start'

  post "/games/:id/submit", to: 'games#addImage'

  get "/games/:id/getImages", to: 'games#getImages'

  post "/games/:id/vote", to: 'games#vote'

  get "/games/:id/winner", to: 'games#winner'

  get "/games/:id/source", to: 'games#source'

  resources :games_images

  resources :source_images

  resources :games

  resources :users

  

  match "/help", to: 'static_pages#help'

end

app/models/games_image.rb
class GamesImage < ActiveRecord::Base
  attr_accessible :gameId, :imageUrl, :userSubmitted, :votes
end

app/controllers/games_images_controller.rb
class GamesImagesController < ApplicationController
  # GET /games_images
  # GET /games_images.json
  def index
    @games_images = GamesImage.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @games_images }
    end
  end

  # GET /games_images/1
  # GET /games_images/1.json
  def show
    @games_image = GamesImage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @games_image }
    end
  end

  # GET /games_images/new
  # GET /games_images/new.json
  def new
    @games_image = GamesImage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @games_image }
    end
  end

  # GET /games_images/1/edit
  def edit
    @games_image = GamesImage.find(params[:id])
  end

  # POST /games_images
  # POST /games_images.json
  def create
    @games_image = GamesImage.new(params[:games_image])

    respond_to do |format|
      if @games_image.save
        format.html { redirect_to @games_image, notice: 'Games image was successfully created.' }
        format.json { render json: @games_image, status: :created, location: @games_image }
      else
        format.html { render action: "new" }
        format.json { render json: @games_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /games_images/1
  # PUT /games_images/1.json
  def update
    @games_image = GamesImage.find(params[:id])

    respond_to do |format|
      if @games_image.update_attributes(params[:games_image])
        format.html { redirect_to @games_image, notice: 'Games image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @games_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games_images/1
  # DELETE /games_images/1.json
  def destroy
    @games_image = GamesImage.find(params[:id])
    @games_image.destroy

    respond_to do |format|
      format.html { redirect_to games_images_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/games_images_helper.rb
module GamesImagesHelper
end

app/views/games_images/_form.html.erb
<%= form_for(@games_image) do |f| %>
  <% if @games_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@games_image.errors.count, "error") %> prohibited this games_image from being saved:</h2>

      <ul>
      <% @games_image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :gameId %><br />
    <%= f.text_field :gameId %>
  </div>
  <div class="field">
    <%= f.label :imageUrl %><br />
    <%= f.text_field :imageUrl %>
  </div>
  <div class="field">
    <%= f.label :votes %><br />
    <%= f.number_field :votes %>
  </div>
  <div class="field">
    <%= f.label :userSubmitted %><br />
    <%= f.text_field :userSubmitted %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games_images/edit.html.erb
<h1>Editing games_image</h1>

<%= render 'form' %>

<%= link_to 'Show', @games_image %> |
<%= link_to 'Back', games_images_path %>

app/views/games_images/index.html.erb
<h1>Listing games_images</h1>

<table>
  <tr>
    <th>Gameid</th>
    <th>Imageurl</th>
    <th>Votes</th>
    <th>Usersubmitted</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @games_images.each do |games_image| %>
  <tr>
    <td><%= games_image.gameId %></td>
    <td><%= games_image.imageUrl %></td>
    <td><%= games_image.votes %></td>
    <td><%= games_image.userSubmitted %></td>
    <td><%= link_to 'Show', games_image %></td>
    <td><%= link_to 'Edit', edit_games_image_path(games_image) %></td>
    <td><%= link_to 'Destroy', games_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Games image', new_games_image_path %>

app/views/games_images/new.html.erb
<h1>New games_image</h1>

<%= render 'form' %>

<%= link_to 'Back', games_images_path %>

app/views/games_images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Gameid:</b>
  <%= @games_image.gameId %>
</p>

<p>
  <b>Imageurl:</b>
  <%= @games_image.imageUrl %>
</p>

<p>
  <b>Votes:</b>
  <%= @games_image.votes %>
</p>

<p>
  <b>Usersubmitted:</b>
  <%= @games_image.userSubmitted %>
</p>


<%= link_to 'Edit', edit_games_image_path(@games_image) %> |
<%= link_to 'Back', games_images_path %>